name: Publish Container

on:
  push:
    branches:
      - main
      - tests/bootstrap

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and Push to GitHub Container Registry
        run: |
          docker build . --tag ghcr.io/sundeepchand/strapi:latest
          docker push ghcr.io/sundeepchand/strapi:latest
        
  publish-test-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and Push the Test Image to GitHub Container Registry
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: strapi-test
          registry: ghcr.io
          dockerfile: Dockerfile.test
          githubOrg: SundeepChand
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
